management:
  security:
    enabled: false

server:
  port: 8081

spring:
  boot:
    admin:
      url: http://localhost:8080/admin-server

info:
  app:
    name: "Spring-Boot-Admin-Client"
    description: "Parent pom providing dependency and plugin management for applications
		built with Maven"
    version: "1.0-SNAPSHOT"
    spring-boot-version: "1.5.9.RELEASE" 
